### ISSUE TITLE
Flexie should parse attached style sheets and return flex properties.

### ISSUE THREAD

**Issue by doctyper** [doctyper/reflexie#15]

**Comment by jonrimmer** [comment]
Could the [parser Adobe wrote for their Regions polyfill](https://github.com/adobe-webplatform/css-regions-polyfill/blob/master/src/cssparser.js) be adapted for use in Reflexie? It seems nice and lightweight.

**Comment by doctyper** [comment]
I'll take a look. Right now I'm leaning towards abstracting Keith Clark's parser from [Selectivizr](https://github.com/keithclark/selectivizr/blob/master/selectivizr.js) as I did in the original Flexie.

**Comment by doctyper** [comment]
Via 5490655cc9
