### ISSUE TITLE
Leverage 2009 spec where present?

### ISSUE THREAD

**Issue by pci** [doctyper/reflexie#17]
This has probably been looked at before, but could we use the 2009 `display: box;` support to do some of the positioning heavy lifting if it's present? It would minimise CPU and render time to leverage existing browser code.

[Caniuse suggests](http://caniuse.com/#search=flex) 30% of desktop users and _over 80% of mobile users_ support the 2009 syntax. For basic use (flex, order and direction) compatibility looks [fairly good](http://css-tricks.com/using-flexbox/), and if it's more advanced than that we could always fall back to reflexie doing all the work.

The main question seems to be: How bad would the edge cases be? Is there a subset of features that we could safely transcribe to the 2009 spec?

**Comment by doctyper** [comment]
Well, there's always a chance that browsers will eventually pull the old flexbox code from their codebase.

What I'd like to do is finish the polyfill without a dependency on the old flexbox model. After that milestone we can revisit bridging the models to take advantage of existing functionality. That way, even if old flexbox goes away Reflexie will still be able to polyfill them.

**Comment by pci** [comment]
Sorry, I don't think I've explained myself well. I was more thinking
if(new spec supported):  return
elseif(old spec supported and basic usage):  translate css to old spec
else:  full reflexie

But you're right, finishing the polyfill before looking at optimisations is the way to go. Do you want me to close the issue or leave it open for the far-future?

Also, what's a good job/issue to get started on and get used to the code?

**Comment by pci** [comment]
Closed as not relevant
