### ISSUE TITLE
Remove align-items tests - no chrome support

### ISSUE THREAD

**Issue by pci** [doctyper/reflexie#21]
We're getting some false fails on the tests because chrome doesn't seems to support align-items yet. In fact I think there are a few of the more obscure parameters that chrome doesn't fully support but align-items seems to be the biggest one.

I'd remove align-items from the tests myself, but I can't figure out how to remake the tests. Am I right in thinking the pair tests get generated from the TSV files? If so what command then needs to be run after you make a change?

**Comment by doctyper** [comment]
Chrome (stable, 25) most definitely has `align-items` support. Check out this demo in Chrome: http://demo.agektmr.com/flexbox/

**Comment by pci** [comment]
That's weird, it works on that site but not on the tests (see attached img) might have something to do with the fact I'm on the dev channel, I'll switch to stable and rerun.

Out of interest, how do you remake the tests?

![Screen Shot 2013-03-23 at 15 39 23](https://f.cloud.github.com/assets/736097/294063/08f58f3e-93d0-11e2-8636-abee59fd4cd3.png)

**Comment by doctyper** [comment]
In the screenshot, you can see that each child is defining its own `align-self` property, which supersedes the parent's `align-items` rule.

The easiest way to modify the TSV file is to drop it into Google Docs, modify, and export it out. To generate tests run from project root:

``` shell
node test/data/pairwise/generate-tests.js
```

**Comment by doctyper** [comment]
Also, note that the `full-suite` files are ignored, they're just there for posterity and for potential future compatibility.

**Comment by pci** [comment]
Ah - I was too caught up in debugging the container properties. As per normal the problem was between the keyboard and chair! Thanks for your help.
