### ISSUE TITLE
how to test "in production"?

### ISSUE THREAD

**Issue by ahti** [doctyper/reflexie#24]
I've cloned the repo and run the test, it seems like reflexie does get some things right already.

I'd love to just try out what works and what doesn't by building a little html myself. Unfortunately I have no idea how to do that. I tried just including `dist/reflexie.min.js` in the html header. That didn't do anything though, even with a simple layout (just a line of boxes). What more do i need to do?

**Comment by doctyper** [comment]
First, I absolutely do not think Flexie is ready for a production environment. Not yet, anyway. API changes are most certainly coming. 

You need to call Flexie.init() before it does anything. This gives you an opportunity to muck with styles before Flexie parses them.
