### ISSUE TITLE
Flex-basis requires processing 

### ISSUE THREAD

**Issue by pci** [doctyper/reflexie#25]
Both flex-wrap and flew-grow/shrink use flex-basis, which can be any standard length: px, % (of the container), em, rem, and of course the list goes on...and on (vw,  vh)...and on (ch?!?). 

Can we create a flexie.util to process the flex-basis string, or is there a library we can use to do the heavy lifting? 

As an indication of how good this would be: hacking px support (the only one we test against) into flex-basis takes the number of fails down to 80!

**Comment by doctyper** [comment]
I think for now it's enough to only support pixel values. You can create a shim Flexie.util that only works with pixels, and we can add support for other suffixes to the wish list. 
(via thumbs)

**Comment by pci** [comment]
Closed as covered by #26
