### ISSUE TITLE
Poll: "Reflexie" or "Flexie 2.0"?

### ISSUE THREAD

**Issue by doctyper** [doctyper/reflexie#30]

**Comment by pci** [comment]
My preference is for Reflexie: it creates a division between the polyfill for the old syntax - flexie and the new syntax - reflexie, and has the nice 'reflex' word play.

**Comment by jonrimmer** [comment]
Why not simply 'Reflex'? I think a problem with 'Flexie' and 'Reflexie' is that they sound like 'Flex IE', which gives the impression that they're only a polyfill for Internet Explorer when people mention them.

**Comment by doctyper** [comment]
@JonRimmer 
![](http://t.qkme.me/3r2sdw.jpg)

**Comment by jonrimmer** [comment]
The joke is deliberately misleading people as to the purpose of the project? Why would you want to do that? I don't really get it...

**Comment by wootfox** [comment]
I agree with @JonRimmer, Reflex is less confusing but still descriptive.

**Comment by andrew-luhring** [comment]
I mean... you could just spell it as 
reflexy
or reflex-e
or reflexeee.
either way we should make it real before we begin a marketing campaign.
sincerely,
some guy on github who hasn't contributed any code yet.

**Comment by doctyper** [comment]
Indeed.
